name: dsait4090
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - pandas
    - numpy
    - openai
    - google-generativeai
    - huggingface_hub
    - python-dotenv
    - tqdm
    - openpyxl